# Dependabot Configuration for .NET Project

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "sunday"
    allow:
      - dependency-type: direct
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
    commit-message:
      prefix: "Dependabot package update"
    open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
